---------------------------------------------
-- Teoria de los Lenguajes de Programacion --
-- Practica del Curso: 2014-2015           --
---------------------------------------------
-- Codigo Haskell con los juegos de prueba --
-- de la practica con nonogramas extraidos --
-- del videojuego Picture Puzzle de MSX.   --
---------------------------------------------

module NonogramasPruebasPicturePuzzle where

import Nonogramas

testPicturePuzzle = putStr ( testPicPuz 1 fasesPicPuz )
testPicPuz _ [] = ""
testPicPuz n (x:xs) = "Fase " ++ (show n) ++ ": el dibujo " ++ (compruebaDibujo x) ++ (testPicPuz (n+1) xs)
  where compruebaDibujo dibujo
          | longitud == 0 = "no genera soluciones\n"
          | longitud == 1 = "genera una unica solucion\n"
          | otherwise     = "genera varias soluciones\n"
            where longitud = length ( take 2 soluciones )
                  soluciones = solucionesNonograma ([],map (generaFila nC) rF,rC,nF)
                  (rF,rC,nF,nC) = creaNonograma dibujo

fasesPicPuz = [[[False,True,True,True,False],[False,True,True,True,False],[False,True,True,True,False],[False,True,True,True,False],[True,True,True,True,True]],
               [[False,True,True,False,False],[True,True,True,False,True],[True,False,True,True,False],[False,False,True,True,False],[False,True,False,False,False]],
               [[True,True,False,True,False],[False,True,False,False,True],[False,True,False,False,True],[False,True,False,False,True],[False,False,True,True,True]],
               [[True,True,True,True,True],[True,False,False,False,True],[True,True,False,True,True],[False,True,True,True,False],[False,False,True,False,False]],
               [[True,True,False,False,False],[False,True,True,False,False],[False,False,True,True,True],[False,False,True,True,True],[False,False,True,True,True]],
               [[False,False,True,True,False],[False,True,False,True,False],[False,False,False,True,False],[False,False,False,True,False],[False,False,False,True,False]],
               [[True,False,False,True,False],[False,True,True,False,False],[False,True,True,False,False],[False,False,True,True,True],[True,True,True,True,True]],
               [[False,True,True,False,False],[True,True,False,False,False],[True,True,True,False,True],[False,True,True,True,False],[True,True,True,True,False]],
               [[True,True,False,False,False],[True,True,True,False,False],[False,False,True,True,True],[True,True,True,True,True],[False,False,False,True,True]],
               [[True,True,False,False,False],[False,True,False,False,False],[False,True,True,False,False],[False,True,True,True,True],[False,False,False,False,True]],
               [[False,True,False,False,False],[True,False,True,False,False],[True,True,True,True,False],[False,False,False,True,True],[False,False,True,False,True]],
               [[True,True,True,False,False],[True,False,True,True,False],[True,False,False,True,True],[True,False,False,False,True],[True,True,True,True,True]],
               [[False,False,False,False,False],[False,True,False,False,False],[True,True,False,False,True],[False,True,True,True,True],[True,True,True,True,False]],
               [[True,False,False,False,False],[False,True,False,False,False],[False,True,True,True,False],[True,True,True,True,True],[False,True,False,False,False]],
               [[False,True,False,False,False],[True,False,True,False,False],[False,False,True,True,False],[False,False,True,True,False],[False,True,True,True,False]],
               [[False,False,True,False,False],[True,True,True,False,True],[True,True,False,True,True],[False,False,False,True,True],[False,False,True,True,False]],
               [[True,False,True,False,False],[True,True,True,False,True],[False,True,False,False,True],[False,False,True,True,False],[False,True,False,True,False]],
               [[True,False,False,False,False],[False,True,True,False,False],[False,True,True,True,True],[False,False,True,True,True],[False,False,True,True,True]],
               [[True,True,False,False,False],[True,True,True,True,True],[False,True,True,True,False],[False,True,False,True,False],[False,True,False,True,False]],
               [[False,False,False,False,False],[False,True,True,True,False],[False,True,True,False,False],[False,True,False,False,False],[False,False,False,False,False]],
               [[False,False,False,False,True,True,False,True,True,False],[False,False,False,True,True,True,True,True,True,False],[False,False,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True]],
               [[False,False,False,True,True,True,True,False,False,False],[False,False,True,True,True,True,True,True,False,False],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True]],
               [[False,False,True,True,True,True,True,True,False,False],[False,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False],[False,False,True,True,True,True,True,True,False,False],[False,True,True,True,True,True,True,True,True,False],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True]],
               [[False,False,False,False,True,True,False,False,False,False],[False,True,True,False,True,False,True,True,True,False],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False],[False,False,True,True,True,True,True,True,False,False]],
               [[False,False,True,False,False,False,True,True,True,True],[False,True,True,True,False,True,True,True,True,True],[True,True,True,True,False,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False],[False,False,True,True,True,True,True,True,False,False],[False,False,True,True,True,True,True,False,False,False],[False,False,True,True,True,True,True,True,True,False],[False,False,False,True,True,True,True,True,True,True],[False,False,False,False,False,True,True,False,True,True],[False,False,False,False,True,True,False,False,False,False]],
               [[False,False,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,True]],
               [[False,False,False,False,False,True,True,True,True,True],[False,True,True,False,False,False,True,True,True,True],[True,True,False,False,False,True,True,True,True,True],[True,False,False,True,True,True,True,True,True,True],[True,False,True,True,True,True,True,True,False,True],[True,True,True,True,True,True,True,False,False,False],[True,False,True,True,True,True,True,False,False,False],[False,True,False,True,True,True,False,False,True,False],[True,False,True,False,True,False,False,True,True,False],[False,True,False,True,True,True,True,True,False,False]],
               [[False,False,False,False,True,True,True,True,False,False],[False,False,False,True,True,True,True,False,False,False],[False,False,True,True,True,True,True,True,False,True],[False,True,True,True,False,True,True,True,True,True],[True,True,True,True,False,True,False,True,True,True],[True,True,True,True,False,True,False,True,False,True],[True,True,False,True,False,True,False,True,True,False],[False,True,True,True,False,True,True,True,True,True],[False,False,True,True,True,True,False,True,False,True],[False,False,False,False,False,True,True,True,False,False]],
               [[False,False,False,False,True,True,False,False,False,False],[False,False,True,True,True,True,True,True,False,False],[False,True,True,True,True,True,True,True,True,False],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,False],[False,False,False,True,True,True,True,False,False,False],[False,False,False,True,True,True,True,False,False,False],[False,True,True,True,True,True,True,True,True,False]],
               [[False,False,True,True,True,True,True,True,False,False],[False,True,True,True,True,True,True,True,True,False],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,False,False,False,False,False,False,True,True],[True,True,True,False,False,False,False,True,True,True],[False,True,True,True,True,True,True,True,True,False],[False,False,True,True,False,False,True,True,False,False],[False,False,False,True,True,True,True,False,False,False]],
               [[False,False,False,True,True,True,True,False,False,False],[False,False,False,True,True,True,True,False,False,False],[True,True,False,True,True,True,True,False,True,True],[True,False,True,True,True,True,True,True,False,True],[True,False,False,True,False,True,True,False,False,True],[True,False,True,True,False,True,True,True,False,True],[False,True,True,False,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False],[False,False,True,True,True,True,True,True,False,False]],
               [[False,False,False,False,True,True,True,True,True,False],[False,True,True,True,True,True,True,False,False,False],[False,False,False,True,True,True,True,True,True,False],[False,False,False,False,True,True,True,False,True,True],[False,False,False,False,True,True,True,True,False,False],[False,False,False,True,True,True,True,True,False,False],[True,True,True,True,True,True,True,True,True,True],[False,False,False,True,True,True,True,True,True,True],[False,False,False,False,True,True,True,False,True,True],[False,False,False,False,False,False,True,False,False,False]],
               [[False,True,True,True,True,True,True,True,True,False],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[False,False,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,False]],
               [[False,False,False,False,False,False,False,True,False,False],[False,False,False,False,False,False,True,True,True,False],[False,False,False,False,True,True,True,True,True,False],[False,False,False,True,True,True,True,True,True,True],[False,False,False,False,True,True,True,True,True,True],[False,False,False,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False],[True,True,False,True,True,True,True,True,False,False],[True,True,True,True,True,True,True,True,False,False],[False,True,True,True,True,True,True,False,False,False]],
               [[False,False,False,True,True,True,True,True,True,True],[False,False,False,True,True,True,True,True,True,True],[False,False,False,True,True,True,True,True,True,True],[False,False,False,False,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,False,True,True,True],[True,True,True,True,True,True,False,False,False,False],[True,True,True,True,True,True,False,False,False,False],[False,True,True,True,True,False,False,False,False,False]],
               [[False,False,False,True,True,True,True,False,False,False],[False,False,True,True,True,True,True,True,False,False],[False,False,True,True,True,True,True,True,False,False],[False,False,True,True,True,True,True,True,False,False],[False,False,True,True,True,True,True,True,False,False],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[False,False,False,True,True,True,True,False,False,False],[False,False,False,True,True,True,True,False,False,False]],
               [[False,False,False,False,True,False,False,False,False,False],[False,False,False,False,True,False,True,False,False,False],[False,False,False,True,True,False,True,False,False,False],[False,False,True,True,True,False,True,True,False,False],[False,True,True,True,True,False,True,True,False,False],[True,True,True,True,True,False,True,True,True,False],[False,False,False,False,True,False,False,False,False,False],[True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,False],[True,True,True,True,True,True,True,True,True,True]],
               [[False,True,True,True,True,True,True,True,True,False],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,False]],
               [[False,False,False,True,True,True,True,False,False,False],[False,False,True,True,True,True,True,False,False,False],[False,False,True,True,True,True,True,False,False,False],[False,False,True,True,True,True,True,False,False,False],[False,False,False,True,True,True,True,False,False,False],[False,False,False,True,True,True,True,False,False,False],[False,False,False,True,True,True,True,False,False,False],[False,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,False]],
               [[False,True,True,True,False,True,True,True,True,True],[True,False,False,True,False,True,False,False,True,True],[True,False,True,False,True,True,False,True,True,True],[True,False,True,True,True,False,False,True,True,True],[True,False,True,True,False,False,True,True,True,True],[True,False,True,False,False,True,True,True,False,False],[True,False,False,False,True,True,True,False,True,True],[True,False,False,True,True,True,True,True,True,True],[True,False,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,False]],
               [[True,True,True,False,False,False,False,False,False,False,False,False,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,False],[False,False,True,True,True,True,True,True,True,True,True,True,True,False,False],[False,False,True,True,True,True,True,True,True,True,True,True,True,False,False],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,False],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,False,False,False,True,True,True,True,True,False]],
               [[False,False,False,False,False,False,True,True,True,True,True,True,False,False,False],[False,False,False,False,True,True,True,True,True,True,True,True,True,False,False],[False,False,False,False,True,True,True,True,True,True,True,True,True,True,False],[False,False,True,True,True,True,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,False],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,False]],
               [[False,False,False,False,False,False,False,False,False,False,False,False,False,True,True],[False,False,False,False,False,False,True,True,True,True,True,True,False,True,True],[False,False,False,False,True,True,True,False,False,False,False,True,True,True,True],[False,False,False,True,True,False,False,False,False,False,False,False,False,True,True],[False,True,True,True,True,True,True,True,True,True,True,False,False,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,False,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,False,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,False,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,False,True,True],[True,True,True,True,True,True,True,True,True,True,True,False,False,True,True],[False,True,True,False,True,True,False,True,True,False,False,False,False,True,True],[False,False,False,False,False,False,False,False,False,True,True,True,True,True,True],[False,False,False,False,False,False,False,False,False,True,True,True,True,True,False]],
               [[False,False,False,False,False,False,True,True,True,False,False,False,False,False,False],[False,False,False,False,False,False,True,True,True,False,False,False,False,False,False],[False,False,False,False,False,True,True,True,True,True,False,False,False,False,False],[False,False,False,False,True,True,True,True,True,True,True,False,False,False,False],[False,False,True,True,True,True,True,True,True,True,True,True,True,False,False],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,False],[True,True,True,True,True,True,True,False,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,False,True,True,True,True,True,True,True],[True,False,True,True,False,True,True,False,True,True,False,True,True,False,True],[True,False,True,True,False,True,True,False,True,True,False,True,True,False,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,False],[False,False,False,False,True,True,True,True,True,True,True,False,False,False,False],[False,False,False,True,True,True,True,True,True,True,True,True,False,False,False]],
               [[False,False,False,False,False,True,True,True,True,True,False,False,False,False,False],[False,False,False,False,True,True,True,False,True,True,True,False,False,False,False],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,False,False,False,False,False,True,False,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[False,True,True,True,False,False,True,False,True,True,True,True,True,True,False],[False,True,True,True,False,False,True,False,True,True,True,True,True,True,False],[False,True,True,True,True,False,True,False,True,True,True,True,True,True,False],[False,True,True,True,True,False,True,False,True,True,True,True,True,True,False],[False,True,True,True,True,False,True,False,True,True,True,True,True,True,False],[False,True,True,True,True,False,True,False,True,True,True,True,True,True,False],[False,False,True,True,True,False,True,False,True,True,True,True,True,False,False],[False,False,True,True,True,False,True,False,True,True,True,True,True,False,False],[False,False,True,True,True,True,True,True,True,True,True,True,True,False,False],[False,False,True,True,True,True,True,True,True,True,True,True,True,False,False]],
               [[False,True,True,True,True,True,True,False,False,False,False,False,True,True,False],[True,True,False,True,False,False,True,True,True,False,False,True,True,True,True],[True,False,True,False,True,False,True,False,True,False,False,True,True,True,True],[True,True,False,True,False,True,False,True,True,True,False,False,True,True,False],[True,False,True,False,True,False,True,False,False,True,False,False,False,False,False],[True,False,False,True,False,True,False,True,False,True,False,False,True,True,False],[True,True,True,False,True,False,True,False,True,True,False,True,True,True,True],[False,True,False,True,False,True,False,True,False,True,False,True,True,True,True],[False,True,True,True,False,False,True,False,True,True,False,False,True,True,False],[False,False,False,True,True,True,True,True,True,True,True,False,False,False,False],[False,False,False,False,False,False,False,False,False,True,True,True,False,False,False],[False,True,True,False,False,False,False,False,False,False,True,True,True,False,False],[True,True,True,True,False,False,False,False,False,False,False,True,True,True,False],[True,True,True,True,False,False,False,False,False,False,False,False,True,True,True],[False,True,True,False,False,False,False,False,False,False,False,False,False,True,True]],
               [[False,False,False,True,True,True,False,False,False,False,False,False,True,True,False],[False,False,True,False,True,False,True,False,False,False,False,False,True,True,True],[False,False,True,False,True,False,True,False,False,False,False,False,False,True,True],[False,False,False,False,True,False,False,False,False,False,True,True,True,True,True],[False,False,True,True,True,True,True,True,False,False,False,True,True,True,True],[False,True,True,True,True,True,True,True,True,False,False,False,False,True,True],[True,True,True,True,True,True,True,True,True,True,True,False,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,True,True,True,False,False,False]],
               [[False,False,True,True,True,False,False,False,False,False,True,True,True,False,False],[False,True,True,True,True,True,False,False,False,True,True,True,True,True,False],[False,True,True,True,True,True,False,False,False,True,True,True,True,True,False],[False,True,True,True,True,True,False,False,False,True,True,True,True,True,False],[False,True,True,True,True,True,False,True,False,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,False],[False,True,True,True,True,True,True,True,True,True,True,True,True,True,False],[True,True,True,True,True,True,True,False,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,False,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,False,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,False,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,False,True,True,True,True,True,True,True],[True,True,True,True,True,True,True,False,True,True,True,True,True,True,True],[False,True,True,True,True,True,False,False,False,True,True,True,True,True,False]],
               [[True,True,True,False,False,False,False,False,False,False,False,False,True,True,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,True,True,True,True,False,False,False,False,False,True,True,True,True,True],[False,True,True,False,False,False,False,False,False,False,False,False,True,True,False],[True,True,False,True,True,True,True,False,True,True,True,True,False,True,True],[True,True,False,True,True,False,True,False,True,False,True,True,False,True,True],[True,False,False,True,True,False,True,False,True,False,True,True,False,False,True],[True,False,False,True,True,True,True,False,True,True,True,True,False,False,True],[True,False,False,True,True,True,True,False,False,True,True,True,False,False,True],[True,True,False,False,False,False,False,False,False,False,False,False,False,True,True],[True,True,True,False,True,False,False,False,False,False,True,False,True,True,True],[False,True,True,True,True,False,True,True,True,False,True,True,True,True,False],[False,False,True,True,True,True,False,True,False,True,True,True,True,False,False],[False,False,False,False,True,True,True,False,True,True,True,False,False,False,False],[False,False,False,False,False,True,True,True,True,True,False,False,False,False,False]],
               [[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,False,False,False,False,False,False,False,False,False,False,False,False,False,True],[True,False,False,True,True,True,True,True,False,False,False,True,True,False,True],[True,False,True,True,True,True,True,True,True,False,False,True,True,False,True],[True,False,True,True,False,True,False,True,True,True,True,True,False,False,True],[True,False,True,True,True,True,True,True,True,False,False,False,False,False,True],[True,False,True,True,False,True,False,True,True,False,False,False,False,False,True],[True,False,True,True,True,True,True,True,True,False,False,True,True,False,True],[True,False,False,True,True,True,True,True,False,False,False,True,True,False,True],[True,False,False,False,False,False,False,False,False,False,False,False,False,False,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True],[True,False,False,False,False,False,False,False,False,False,False,False,False,False,True],[True,False,True,True,False,False,True,False,True,False,True,False,True,False,True],[True,False,True,True,False,False,False,False,False,False,False,False,True,False,True],[True,True,True,True,True,True,True,True,True,True,True,True,True,True,True]]]

mostrarNonogramas = mostrarNonogramas' fasesPicPuz
	where
	mostrarNonogramas' (x:xs) = resuelveNonograma ( creaNonograma (x)) ++ mostrarNonogramas' xs
	mostrarNonogramas' _ = ""

mostrarNonogramasPicturePuzzle = putStr (mostrarNonogramas)
